# Foundry Configuration File
# Default definitions: https://github.com/gakonst/foundry/blob/b7917fa8491aedda4dd6db53fbb206ea233cd531/config/src/lib.rs#L782
# See more config options at: https://github.com/gakonst/foundry/tree/master/config

[profile.default]
solc_version = '0.8.18'
src = "contracts"
out = "out"
test = 'foundry-test'
libs = ['lib']
optimizer = true
optimizer_runs = 200
via_ir = true
ffi = true
gas_limit = '18446744073709551615'
remappings = [
    "@ensdomains/=node_modules/@ensdomains/",
    "hardhat-deploy/=node_modules/hardhat-deploy/",
    "hardhat/=node_modules/hardhat/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "solmate/=node_modules/solmate/"
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config